### ISSUE TITLE
cuDNN v8.8.0 for aarch64 + CUDA 12 is not consumable by recipe maintainers

### ISSUE THREAD

**Issue by leofang** [conda-forge/cudnn-feedstock#58]
When working on https://github.com/conda-forge/cupy-feedstock/pull/199 I noticed I kept hitting [this mysterious error](https://app.travis-ci.com/github/conda-forge/cupy-feedstock/jobs/601758986):
```
586 Mamba failed to solve:
587 - cython >=0.29.22,<3
588 - pip
589 - libcufft-dev
590 - fastrlock >=0.5
591 - cudnn >=7.6
592 - libcublas-dev
593 - cutensor >=1.4,<2
594 - libcusparse-dev
595 - cuda-cccl_linux-aarch64
596 - python 3.10.* *_cpython
597 - libcusolver-dev
598 - cuda-profiler-api
599 - libcurand-dev
600 - cuda-nvrtc-dev
601 - cuda-version 12.0.*
602 - cuda-driver-dev
603 - setuptools
604 - cuda-cudart-dev
605 - python
606 - cuda-nvtx-dev
607
608with channels:
609
610The reported errors are:
611- Encountered problems while solving:
612-   - package libcurand-dev-10.3.1.50-ha21bd82_0 requires cuda-version >=12.0.0,<12.1.0a0, but none of the providers can be installed
613- 
614
615Leaving build/test directories:
616  Work:
617 /home/conda/feedstock_root/build_artifacts/work 
618  Test:
619 /home/conda/feedstock_root/build_artifacts/test_tmp 
620Leaving build/test environments:
621  Test:
622source activate  /home/conda/feedstock_root/build_artifacts/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_ 
623  Build:
624source activate  /home/conda/feedstock_root/build_artifacts/_build_env 
625
626
627Traceback (most recent call last):
628  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 141, in mamba_get_install_actions
629    solution = solver.solve_for_action(_specs, prefix)
630  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 230, in solve_for_action
631    t = self.solve(specs)
632  File "/opt/conda/lib/python3.10/site-packages/boa/core/solver.py", line 220, in solve
633    raise RuntimeError("Solver could not find solution." + error_string)
634RuntimeError: Solver could not find solution.Mamba failed to solve:
635 - cython >=0.29.22,<3
636 - pip
637 - libcufft-dev
638 - fastrlock >=0.5
639 - cudnn >=7.6
640 - libcublas-dev
641 - cutensor >=1.4,<2
642 - libcusparse-dev
643 - cuda-cccl_linux-aarch64
644 - python 3.10.* *_cpython
645 - libcusolver-dev
646 - cuda-profiler-api
647 - libcurand-dev
648 - cuda-nvrtc-dev
649 - cuda-version 12.0.*
650 - cuda-driver-dev
651 - setuptools
652 - cuda-cudart-dev
653 - python
654 - cuda-nvtx-dev
655
656with channels:
657
658The reported errors are:
659- Encountered problems while solving:
660-   - package libcurand-dev-10.3.1.50-ha21bd82_0 requires cuda-version >=12.0.0,<12.1.0a0, but none of the providers can be installed
661- 
662
663During handling of the above exception, another exception occurred:
664
665Traceback (most recent call last):
666  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
667    sys.exit(main())
668  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
669    call_conda_build(action, config)
670  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
671    result = api.build(
672  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
673    return build_tree(
674  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3078, in build_tree
675    packages_from_this = build(metadata, stats,
676  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2038, in build
677    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
678  File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 787, in expand_outputs
679    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
680  File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
681    conda_packages = finalize_outputs_pass(
682  File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 879, in finalize_outputs_pass
683    parent_metadata.parse_until_resolved()
684  File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1270, in parse_until_resolved
685    self.parse_again(
686  File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1167, in parse_again
687    self._get_contents(
688  File "/opt/conda/lib/python3.10/site-packages/conda_build/metadata.py", line 1872, in _get_contents
689    rendered = template.render(environment=env)
690  File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
691    self.environment.handle_exception()
692  File "/opt/conda/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
693    raise rewrite_traceback_stack(source=source)
694  File "/home/conda/recipe_root/meta.yaml", line 105, in top-level template code
695    - pip
696  File "/opt/conda/lib/python3.10/site-packages/conda_build/jinja_context.py", line 234, in pin_compatible
697    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
698  File "/opt/conda/lib/python3.10/site-packages/conda_build/render.py", line 131, in get_env_dependencies
699    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
700  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 150, in mamba_get_install_actions
701    raise err
702conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-aarch64: {MatchSpec("cuda-version[version='>=12.0.0,<12.1.0a0']"), MatchSpec("libcurand-dev==10.3.1.50=ha21bd82_0")}
703The command "if [[ ${PLATFORM} =~ .*linux.* ]]; then CONDA_FORGE_DOCKER_RUN_ARGS="--network=host --security-opt=seccomp=unconfined" travis_wait 120 ./.scripts/run_docker_build.sh; fi" exited with 1.
```
After some digging it turns out to be a `cudnn` issue. @jakirkham came up with the idea, and I confirmed locally, that it's due to the glibc requirement, which was worked around in #56 by using a newer docker image, but this workaround does not propagate to downstream recipes. Apparently, the solver got confused and did not complain about glibc, but instead mistakenly complained about something irrelevant.

**Comment by leofang** [comment]
xref: https://github.com/conda-forge/cupy-feedstock/pull/223#issuecomment-1699359837

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render
